# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
    pgdata:
    walletstore:

networks:
    mynetwork.com:
        name: cotton-dev
        external: true

services:
    explorerdb.mynetwork.com:
        image: hyperledger/explorer-db:latest
        container_name: explorerdb.mynetwork.com
        hostname: explorerdb.mynetwork.com
        environment:
            - DATABASE_DATABASE=fabricexplorer
            - DATABASE_USERNAME=hppoc
            - DATABASE_PASSWORD=password
        healthcheck:
            test: 'pg_isready -h localhost -p 5432 -q -U postgres'
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - mynetwork.com
